"""Add description field to Beta model

Revision ID: 18353115a3d5
Revises: 
Create Date: 2025-09-12 16:35:05.662661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18353115a3d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beta', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
